### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by apitux** [rxlacroix/CarteTopo#3]
Merci et bravo Romain pour ce travail.

Accepterais-tu d'y apposer une licence libre, CC BY-SA par exemple ?

Merci

**Comment by rxlacroix** [comment]
c'est fait :)

**Comment by apitux** [comment]
Le 04/05/2020 17:48, Romain Lacroix a écrit :
> c'est fait :)

Bonjour Romain,

Merci pour ta réactivité !

Je viens de parler de ton travail sur Dessinetaville, la liste de
diffusion sur laquelle je partage ma veille autour d'OpenStreetMap mais
aussi de l'opendata et des communs numériques.

Carte topographique : styles QGIS pour données libres - CarteTopo par
rxlacroix du Cesbio
https://ml.apitux.net/pipermail/dessinetaville/2020-May/000630.html

Bonne continuation

JCB
-- 
Libérez vos créations
http://www.apitux.org/index.php?2008/05/03/232-liberez-vos-creations

==============APITUX : le choix du logiciel libre==============

APITUX - Jean-Christophe Becquet
2 chemin du Tivoli - 04000 Digne-les-Bains
06 25 86 07 92 - jcb@apitux.com - http://www.apitux.com
SIRET : 452 887 441 00031 - APE : 6202A

===============================================================

**Comment by rxlacroix** [comment]
Salut, 

Pas de soucis, merci pour le partage !

En revanche, je ne suis affilié en aucune façon avec le CESBIO, je travaille dans le milieu viticole ;-)

Bonne journée,

**Comment by DelazJ** [comment]
Bonjour,
Je ne l'ai pas sérieusement lu en détail (et encore moins suivi) mais je tenais à dire que j'ai aimé le readme et tous ses gifs... et impressionné par le travail qu'il y a derrière. 👏
